forge "http://forgeapi.puppetlabs.com"

# Modules from the Puppet Forge
mod "puppetlabs/concat", "1.2.3"
mod "puppetlabs/firewall", "1.7.0"
mod "puppetlabs/gcc", "0.3.0"
mod "puppetlabs/git", "0.4.0"
mod "puppetlabs/haproxy", "1.2.0"
mod "puppetlabs/inifile", "1.4.0"
mod "puppetlabs/ntp", "4.0.0"
mod "puppetlabs/pe_gem", "0.1.1"
mod "puppetlabs/puppetserver_gem","0.1.0"
mod "puppetlabs/ruby", "0.4.0"
mod "puppetlabs/stdlib"
mod "reidmv/puppet_certificate"
